CREATE PROCEDURE SP_SPED_FISCAL_REGISTROD120 (
    CD_EMPRESA VARCHAR(3),
    NR_SEQNF VARCHAR(7))
RETURNS (
    COD_MUN_ORIG VARCHAR(7),
    COD_MUN_DEST VARCHAR(7),
    VEIC_ID VARCHAR(7),
    UF_ID VARCHAR(2))
AS
BEGIN

    FOR
    SELECT
    '0000001' AS COD_MUN_ORIG,
    '0000002' AS COD_MUN_DEST,
    'XYZ5101' AS VEIC_ID,
    'SP' AS UF_ID
    FROM RDB$DATABASE
    UNION
    SELECT
    '0000003' AS COD_MUN_ORIG,
    '0000004' AS COD_MUN_DEST,
    'ABC5678' AS VEIC_ID,
    'SP' AS UF_ID
    FROM RDB$DATABASE
    INTO
        :COD_MUN_ORIG,
        :COD_MUN_DEST,
        :VEIC_ID,
        :UF_ID
    DO
    BEGIN

        SUSPEND;

    END


END
