CREATE PROCEDURE SP_SPED_FISCAL_REGISTRO1400 (
    CD_EMPRESA VARCHAR(3),
    DT_EMI_INICIAL DATE,
    DT_EMI_FINAL DATE)
RETURNS (
    COD_ITEM VARCHAR(60),
    MUN VARCHAR(7),
    VALOR NUMERIC(15,2)
)
AS
BEGIN

    -- FILTRAR INFORMAÇÕES DA TABELA NOTALF COM BASE NOS PARÂMETROS
    -- FORNECIDOS ACIMA

    FOR SELECT
        '0000007' AS COD_ITEM,
        '0000008' AS MUN,
        0.01 AS VALOR
        FROM RDB$DATABASE
        UNION
        SELECT
        '0000013' AS COD_ITEM,
        '0000014' AS MUN,
        1.01 AS VALOR
        FROM RDB$DATABASE
    INTO
        :COD_ITEM,
        :MUN,
        :VALOR
    DO
    BEGIN
        SUSPEND;
    END

END
