CREATE PROCEDURE SP_SPED_FISCAL_REGISTRO1600 (
    CD_EMPRESA VARCHAR(3),
    DT_EMI_INICIAL DATE,
    DT_EMI_FINAL DATE)
RETURNS (
    COD_PART VARCHAR(60),
    TOT_CREDITO NUMERIC(15,2),
    TOT_DEBITO NUMERIC(15,2)
)
AS
BEGIN

    FOR
    SELECT
        '0000120' AS COD_PART,
        0.01 AS TOT_CREDITO,
        0.02 AS TOT_DEBITO
    FROM RDB$DATABASE
    UNION
    SELECT
        '0000121' AS COD_PART,
        1.01 AS TOT_CREDITO,
        1.02 AS TOT_DEBITO
    FROM RDB$DATABASE
    INTO
        :COD_PART,
        :TOT_CREDITO,
        :TOT_DEBITO
    DO
    BEGIN
        SUSPEND;
    END

END
