CREATE PROCEDURE SP_SPED_FISCAL_REGISTRO1710 (
    CD_EMPRESA VARCHAR(3),
    DT_EMI_INICIAL DATE,
    DT_EMI_FINAL DATE,
    COD_DISP VARCHAR(2),
    COD_MOD VARCHAR(2),
    SER VARCHAR(4),
    SUB VARCHAR(3)
)
RETURNS (
    NUM_DOC_INI VARCHAR(12),
    NUM_DOC_FIN VARCHAR(12)
)
AS
BEGIN

    FOR
    SELECT
        '000001' AS NUM_DOC_INI,
        '000002' AS NUM_DOC_FIN
    FROM RDB$DATABASE
    UNION
    SELECT
        '000003' AS NUM_DOC_INI,
        '000004' AS NUM_DOC_FIN
    FROM RDB$DATABASE
    INTO
        NUM_DOC_INI,
        NUM_DOC_FIN
    DO
    BEGIN
        SUSPEND;
    END

END
