CREATE PROCEDURE SP_SPED_FISCAL_REGISTRO1210 (
    CD_EMPRESA VARCHAR(3),
    DT_EMI_INICIAL DATE,
    DT_EMI_FINAL DATE,
    COD_AJ_APUR VARCHAR(8)
)
RETURNS (
    TIPO_UTIL VARCHAR(4),
    NR_DOC VARCHAR(100),
    VL_CRED_UTIL NUMERIC(15,2)
)
AS
BEGIN

    FOR
    SELECT
        '0001' AS TIPO_UTIL,
        '1111111111' AS NR_DOC,
        0.05 AS VL_CRED_UTIL
    FROM RDB$DATABASE
    UNION
    SELECT
        '0002' AS TIPO_UTIL,
        '2222222222' AS NR_DOC,
        1.05 AS VL_CRED_UTIL
    FROM RDB$DATABASE
    INTO
        :TIPO_UTIL,
        :NR_DOC,
        :VL_CRED_UTIL
    DO
    BEGIN
        SUSPEND;
    END

END
