CREATE PROCEDURE SP_SPED_FISCAL_REGISTROD130 (
    CD_EMPRESA VARCHAR(3),
    NR_SEQNF VARCHAR(7))
RETURNS (
    COD_PART_CONSG VARCHAR(60),
    COD_PART_RED VARCHAR(60),
    COD_MUN_ORIG VARCHAR(7),
    COD_MUN_DEST VARCHAR(7),
    OTM VARCHAR(100),
    IND_NAT_FRT VARCHAR(1),
    VL_LIQ_FRT NUMERIC(15,2),
    VL_GRIS NUMERIC(15,2),
    VL_PDG NUMERIC(15,2),
    VL_OUT NUMERIC(15,2),
    VL_FRT NUMERIC(15,2),
    VEIC_ID VARCHAR(7),
    UF_ID VARCHAR(2))
AS
BEGIN

    FOR
    SELECT
    '0000020' AS COD_PART_CONSG,
    '0000021' AS COD_PART_RED,
    '0000001' AS COD_MUN_ORIG,
    '0000002' AS COD_MUN_DEST,
    '123' AS OTM,
    '0' AS IND_NAT_FRT,
    0.01 AS VL_LIQ_FRT,
    0.02 AS VL_GRIS,
    0.03 AS VL_PDG,
    0.04 AS VL_OUT,
    0.05 AS VL_FRT,
    'XYZ5101' AS VEIC_ID,
    'SP' AS UF_ID
    FROM RDB$DATABASE
    UNION
    SELECT
    '0000020' AS COD_PART_CONSG,
    '0000021' AS COD_PART_RED,
    '0000003' AS COD_MUN_ORIG,
    '0000004' AS COD_MUN_DEST,
    '4567' AS OTM,
    '1' AS IND_NAT_FRT,
    1.01 AS VL_LIQ_FRT,
    2.02 AS VL_GRIS,
    3.03 AS VL_PDG,
    4.04 AS VL_OUT,
    5.05 AS VL_FRT,
    'ABC5678' AS VEIC_ID,
    'SP' AS UF_ID
    FROM RDB$DATABASE
    INTO
        :COD_PART_CONSG,
        :COD_PART_RED,
        :COD_MUN_ORIG,
        :COD_MUN_DEST,
        :OTM,
        :IND_NAT_FRT,
        :VL_LIQ_FRT,
        :VL_GRIS,
        :VL_PDG,
        :VL_OUT,
        :VL_FRT,
        :VEIC_ID,
        :UF_ID
    DO
    BEGIN

        SUSPEND;

    END


END
