CREATE PROCEDURE SP_SPED_FISCAL_REGISTROD590 (
    CD_EMPRESA VARCHAR(3),
    NR_SEQNF VARCHAR(7))
RETURNS (
    CST_ICMS VARCHAR(7),
    CFOP VARCHAR(4),
    ALIQ_ICMS NUMERIC(15,4),
    VL_OPR NUMERIC(15,2),
    VL_BC_ICMS NUMERIC(15,2),
    VL_ICMS NUMERIC(15,2),
    VL_BC_ICMS_UF NUMERIC(15,2),
    VL_ICMS_UF NUMERIC(15,2),
    VL_RED_BC NUMERIC(15,2),
    COD_OBS VARCHAR(6))
AS
BEGIN

    FOR
    SELECT
    '001' AS CST_ICMS,
    '5101' AS CFOP,
    10 AS ALIQ_ICMS,
    1.01 AS VL_OPR,
    2.02 AS VL_BC_ICMS,
    3.03 AS VL_ICMS,
    2.12 AS VL_BC_ICMS_UF,
    3.13 AS VL_ICMS_UF,
    4.04 AS VL_RED_BC,
    NULL AS COD_OBS
    FROM RDB$DATABASE
    UNION
    SELECT
    '002' AS CST_ICMS,
    '5102' AS CFOP,
    12 AS ALIQ_ICMS,
    5.01 AS VL_OPR,
    6.02 AS VL_BC_ICMS,
    7.03 AS VL_ICMS,
    6.12 AS VL_BC_ICMS_UF,
    7.13 AS VL_ICMS_UF,
    8.04 AS VL_RED_BC,
    NULL AS COD_OBS
    FROM RDB$DATABASE
    INTO
        :CST_ICMS,
        :CFOP,
        :ALIQ_ICMS,
        :VL_OPR,
        :VL_BC_ICMS,
        :VL_ICMS,
        :VL_BC_ICMS_UF,
        :VL_ICMS_UF,
        :VL_RED_BC,
        :COD_OBS
    DO
    BEGIN

        SUSPEND;

    END


END
