CREATE PROCEDURE SP_SPED_FISCAL_REGISTRO1105 (
    CD_EMPRESA VARCHAR(3),
    DT_EMI_INICIAL DATE,
    DT_EMI_FINAL DATE,
    NRO_DE VARCHAR(11)
)
RETURNS (
    PK_NOTAFIS VARCHAR(7),
    COD_MOD VARCHAR(2),
    SERIE VARCHAR(3),
    NUM_DOC VARCHAR(9),
    CHV_NFE VARCHAR(44),
    DT_DOC DATE,
    COD_ITEM VARCHAR(60)
)
AS
BEGIN

    -- PK_NOTAFIS DEVERÁ RETORNAR O VALOR DO CAMPO NR_SEQNF DE NOTALF

    FOR SELECT
        '0000001' AS NR_SEQNF,
        '01' AS COD_MOD,
        '001' AS SERIE,
        '000000001' AS NUM_DOC,
        '1' AS CHV_NFE,
        :DT_EMI_INICIAL AS DT_DOC,
        '0000062' AS COD_ITEM
        FROM RDB$DATABASE
        UNION
        SELECT
        '0000002' AS NR_SEQNF,
        '02' AS COD_MOD,
        '002' AS SERIE,
        '000000002' AS NUM_DOC,
        '2' AS CHV_NFE,
        :DT_EMI_INICIAL AS DT_DOC,
        '0000081' AS COD_ITEM
        FROM RDB$DATABASE
    INTO
        :PK_NOTAFIS,
        :COD_MOD,
        :SERIE,
        :NUM_DOC,
        :CHV_NFE,
        :DT_DOC,
        :COD_ITEM
    DO
    BEGIN
        SUSPEND;

    END

END
